vo=gpu-next
profile=high-quality
hwdec=auto-copy
hwdec-codecs=all
ao=avfoundation
#osc=no #(enable if used with custom lua osc)
#audio-device=avfoundation/~:AMS2_Aggregate:0 #(that's the hack to use spatial audio on macos, research if you need it)
audio-channels=auto
no-hidpi-window-scale
force-window=immediate
geometry=1280x720 #(makes the inital windows comfortable size)
ontop #(personal preference)

script-opts=ytdl_hook-ytdl_path=/opt/homebrew/bin/yt-dlp #(don't forget to install it via "brew install yt-dlp")
stop-screensaver=always

ytdl-format="bestvideo[height<=?2160]+(bestaudio[format_note*=original]/bestaudio)/best" #(best quality without auto dubbed sound)
hls-bitrate=max
ytdl-raw-options=format-sort="res:2160, codec, br, fps"

screenshot-tag-colorspace=no
audio-file-auto=fuzzy
alang=eng,en,english,original #(personal preference, change as needed)

dither=ordered
dither-depth=auto
target-prim=auto
target-trc=auto
reset-on-next-file=audio-delay,mute,pause,speed,sub-delay,video-aspect-override,video-pan-x,video-pan-y,video-rotate,video-zoom,volume
blend-subtitles=yes
video-sync=display-resample
interpolation=no #(enable if want image smoothing)
interpolation-preserve=yes
tscale=oversample
dscale=mitchell
correct-downscaling=yes
linear-downscaling=yes
scale=ewa_lanczos
cscale=spline36
sigmoid-upscaling=yes

sub=no
save-position-on-quit=yes
cache=yes
demuxer-max-bytes=500MiB
demuxer-max-back-bytes=100MiB
cache-secs=60
demuxer-donate-buffer=no
deband=no
cursor-autohide=300
volume=100 #(soft volume should always be at 100% and changed via macos settings only)
hr-seek=yes
no-cache-pause

brightness=0
gamma=0
contrast=0

[hdr] #Infuse player is still better at hdr no matter the settings 
profile-cond=p.video_params and (p.video_params.gamma == "pq" or p.video_params.gamma == "hlg")
profile-restore=copy
target-colorspace-hint=yes
tone-mapping=spline
hdr-compute-peak=yes
target-peak=500

[fs-margin-top] #(personal preference to have the imaged centered physically with the notch)
profile-restore=copy
profile-cond=fullscreen
video-margin-ratio-bottom=0.04

